services:
  app:
    image: yexca/matuya-register:v1.1
    build: .
    ports:
      - "8926:8926"
    env_file:
      - .env
    volumes:
      - matuya_data:/data
    restart: unless-stopped

volumes:
  matuya_data:
